### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [TiMaTiFeY/JavaRealisationClass#1]
1. Не совсем понял, зачем Вы везде берёте `substring` от названия цвета.
1. Зачем в `getFace` Вы проверяете диапазон? Там же на входе `enum`, компилятор не даст передать ничего другого (в этом и есть одно из преимуществ `enum`).
1. Не обязательно создавать новый `Face` при повороте, можно просто заменять в нём массив. Или тогда уж сделайте его поля `final`, если хотите immutable класс.
1. Раз у Вас `Face` не статический, то он имеет доступ к полям внешнего класса. Поэтому незачем ему самому хранить размер, ведь он одинаков у всех граней одного куба.
1. `moveFace`, насколько я понял, позволяет либо повернуть слой `delta`, либо все слои от 0 до `delta`. Мне кажется было бы логичнее задавать два индекса слоя (от и до), чтобы можно было повернуть, например, 2, 3 и 4 слои кубика с ребром 8 разом.
1. `bufferLine` в принципе не очень нужен, можно обойтись одной `int` переменной внутри цикла поворота.
1. В `cubeRotateTo` можно обойтись без пересоздания массива `currentLookingFaces`.
1. В принципе, вместо `randomIntInRange0To()` можно воспользоваться классом `Random` и его методом `nextInt`.
1. Вместо сложения строк внутри вызова `StringBuilder.append` лучше вызвать его для каждого слагаемого.
1. Напишите тесты.

**Comment by timatifey** [comment]
1) Убрал `substring`
2) Убрал проверку в `getFace()`
3) В `rotateFace` теперь создается новый `int[][] newColors` массив, затем его запись
в `Face.colors`
4) `faceSize` удален
5) Добавлен параметр `secondDelta`
6) `int[] bufferLine` -> `int bufferColor`
7) Мне кажется, что это невозможно. Можно не пересоздавать `currentLookingFaces`, но придется создать массив, который будет буффером для индексов. Если этого не будет, замена элементов будет нарушена.
8) `randomIntInRange0To()` -> `Random().nextInt()`
9) В `toString()` в `StringBuilder` теперь элементы добавляются по одному.
10) Какие тесты можно написать для этого?

**Comment by maximpetrov** [comment]
**7** Не согласен, это же обычное циклическое переприсваивание, достаточно просто правильно выбрать порядок переприсваивания. Например, для `UP` Вам нужно элементы следующим образом: `TOP` -> `FRONT` -> `BOTTOM` -> `BACK`. В случае правильного порядка Вам хватит одной временной переменной. И главное, что в таком случае Вы не будете завязаны на порядок элементов в `enum`: сейчас это, вроде бы, единственное место, где всё сломается при перестановке элементов (в остальных местах Вы используете `ordinal()`).
**10** Как раз тут тесты придумать несложно. Как минимум нужно проверить все повороты: кубика, переднего слоя, нескольких слоёв, причём в каждом из 12 направлений (6 сторон каждую по часовой и против часовой стрелки).

**Comment by timatifey** [comment]
7) Действительно, был не прав, исправил на циклическое переписывание.
10) Написал тесты, добавлены функции `equals()`

**Comment by maximpetrov** [comment]
Когда смотрел реализацию Вашего коллеги и понял, что у Вас в `moveFace` не учтён случай, когда будет повёрнута "задняя" грань (т.е. `secondDelta` будет задана `last`). Задание уже зачтено, так что можете это не исправлять, если не хотите.
